// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVHTLcUiMgUwmGXId4ayuJO1Z6ZgYFlJ0',
    appId: '1:12302949809:web:63fc814fc3dce01f10f190',
    messagingSenderId: '12302949809',
    projectId: 'todo-firestore-4480e',
    authDomain: 'todo-firestore-4480e.firebaseapp.com',
    storageBucket: 'todo-firestore-4480e.firebasestorage.app',
    measurementId: 'G-P5VJTBP7VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABA_pfwLm6goEyp0LmANI8eViwD42UlP8',
    appId: '1:12302949809:android:8b9c0e10b86f9e6410f190',
    messagingSenderId: '12302949809',
    projectId: 'todo-firestore-4480e',
    storageBucket: 'todo-firestore-4480e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv26EgXHNfLKJaRSNP8DSou_zDTTA8Ty4',
    appId: '1:12302949809:ios:39b3d1e83da452ce10f190',
    messagingSenderId: '12302949809',
    projectId: 'todo-firestore-4480e',
    storageBucket: 'todo-firestore-4480e.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv26EgXHNfLKJaRSNP8DSou_zDTTA8Ty4',
    appId: '1:12302949809:ios:39b3d1e83da452ce10f190',
    messagingSenderId: '12302949809',
    projectId: 'todo-firestore-4480e',
    storageBucket: 'todo-firestore-4480e.firebasestorage.app',
    iosBundleId: 'com.example.flutterPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVHTLcUiMgUwmGXId4ayuJO1Z6ZgYFlJ0',
    appId: '1:12302949809:web:d7d78f7fc60866d110f190',
    messagingSenderId: '12302949809',
    projectId: 'todo-firestore-4480e',
    authDomain: 'todo-firestore-4480e.firebaseapp.com',
    storageBucket: 'todo-firestore-4480e.firebasestorage.app',
    measurementId: 'G-3JMGGRBC73',
  );
}
